sitegate:
  build: .
  dockerfile: Dockerfile-dev
  links:
    - db:mongo
    - db:client_mongo
    - db:oauth_mongo
    - db:session_mongo
  volumes:
    - .:/src
  ports:
    - 3000:3000
    - 7171:7171
    - 9595:9595
    - 2769:2769
  environment:
    NODE_ENV: development

db:
  image: mongo
