amqp:
  login: guest
  password: guest
  address: localhost
  port: 5672
session:
  secret: sitegate-secret
facebook:
  clientID: '391179464377243'
  clientSecret: edfafc7715060f8cb4c7212833a3c87a
  callbackURL: https://account.sitegatedev.com:3000/auth/facebook/callback
twitter:
  clientID: j5UFdNnFLv6t24syOiDglfRIX
  clientSecret: GZMmhyaUcsaQULXQknfmXCEh8KTG91UGBeQED19ASvhsaDO7Ba
  callbackURL: https://account.sitegatedev.com:3000/auth/twitter/callback
google:
  clientID: 295363747259-4f4o7483ce5q74a6v31n05s23ke37dii.apps.googleusercontent.com
  clientSecret: rcBTWhsCnytAl6bXr3iTnjPs
  callbackURL: https://account.sitegatedev.com:3000/auth/google/callback
linkedin:
  clientID: APP_ID
  clientSecret: APP_SECRET
  callbackURL: http://localhost:3000/auth/linkedin/callback
github:
  clientID: APP_ID
  clientSecret: APP_SECRET
  callbackURL: http://localhost:3000/auth/github/callback
userService:
  mongodb:
    address: localhost
    port: 27017
    name: sitegate-user-dev
clientService:
  mongodb:
    address: localhost
    port: 27017
    name: sitegate-client-dev
oauthService:
  mongodb:
    address: localhost
    port: 27017
    name: sitegate-oauth-dev
sessionService:
  mongodb:
    address: localhost
    port: 27017
    name: sitegate-session-dev
mailerService:
  mailer:
    from: MAILER_FROM
    options:
      service: MAILER_SERVICE_PROVIDER
      auth:
        user: MAILER_EMAIL_ID
        pass: MAILER_PASSWORD
  app:
    title: SiteGate
    host: "https://account.sitegatedev.com:3000"
