app:
  title: SiteGate
amqp:
  login: guest
  password: guest
  address: localhost
  port: 5672
session:
  secret: sitegate-secret
provider:
  facebook:
    provider: facebook
    password: j0f43bslregf
    clientId: '391179464377243'
    clientSecret: edfafc7715060f8cb4c7212833a3c87a
  twitter:
    provider: twitter
    password: j0f43bslregf
    clientId: j5UFdNnFLv6t24syOiDglfRIX
    clientSecret: GZMmhyaUcsaQULXQknfmXCEh8KTG91UGBeQED19ASvhsaDO7Ba
  google:
    provider: google
    password: j0f43bslregf
    clientId: 295363747259-4f4o7483ce5q74a6v31n05s23ke37dii.apps.googleusercontent.com
    clientSecret: rcBTWhsCnytAl6bXr3iTnjPs
    location: https://account.sitegatedev.com:3000/auth/google/callback
  linkedin:
    provider: linkedin
    password: j0f43bslregf
    clientId: APP_ID
    clientSecret: APP_SECRET
    callbackURL: http://localhost:3000/auth/linkedin/callback
  github:
    provider: github
    password: j0f43bslregf
    clientId: c4f9bdc5e1db4b2ac6d2
    clientSecret: 42650e389750c1aff846daf26dd049a3e627a695
userService:
  mongodb:
    address: localhost
    port: 27017
    name: sitegate-user-dev
clientService:
  mongodb:
    address: localhost
    port: 27017
    name: sitegate-client-dev
oauthService:
  mongodb:
    address: localhost
    port: 27017
    name: sitegate-oauth-dev
sessionService:
  mongodb:
    address: localhost
    port: 27017
    name: sitegate-session-dev
mailerService:
  mailer:
    from: 'test-no-reply@example.com'
    options:
      auth:
        api_key: 'api_key'
        domain: 'mg.example.com'
  app:
    title: SiteGate
    host: "https://account.sitegatedev.com:3000"
